import Foundation

/// In-memory representation of one opened Markdown document.
///
/// This model remains deliberately simple for a v1 viewer:
/// - source file URL
/// - raw Markdown text
/// - optional rendered HTML cache
struct MarkdownDocument: Identifiable {
    /// Stable identity used by SwiftUI when needed.
    let id = UUID()

    /// Absolute file URL for the opened Markdown source.
    let fileURL: URL

    /// Raw Markdown text loaded from disk.
    let rawMarkdown: String

    /// Cached rendered HTML generated by `MarkdownRenderService`.
    var renderedHTML: String?

    /// Convenience display name used in the window title.
    var filename: String {
        fileURL.lastPathComponent
    }

    /// Base folder used to resolve relative links and images.
    var baseDirectoryURL: URL {
        // Force directory semantics so relative URL resolution behaves
        // predictably (`sample-image.png` resolves within the Markdown file's
        // folder rather than potentially one level above).
        URL(
            fileURLWithPath: fileURL.deletingLastPathComponent().path,
            isDirectory: true
        )
    }
}
